// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThMoCo.Api.Data;

#nullable disable

namespace ThMoCo.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250103113155_cvvToStringNotInt")]
    partial class cvvToStringNotInt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ThMoCo.Api.DTO.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("ThMoCo.Api.DTO.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Fund")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PaymentCardId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAuthId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId")
                        .IsUnique()
                        .HasFilter("[AddressId] IS NOT NULL");

                    b.HasIndex("PaymentCardId")
                        .IsUnique()
                        .HasFilter("[PaymentCardId] IS NOT NULL");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("ThMoCo.Api.DTO.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ThMoCo.Api.DTO.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<decimal>("PricePerUnit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("ThMoCo.Api.DTO.PaymentCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CardHolderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cvv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpiryDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PaymentCards");
                });

            modelBuilder.Entity("ThMoCo.Api.DTO.ProductDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "category");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "createdDate");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "description");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "imageUrl");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit")
                        .HasAnnotation("Relational:JsonPropertyName", "isAvailable");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasAnnotation("Relational:JsonPropertyName", "price");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "stockQuantity");

                    b.Property<string>("Supplier")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "supplier");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "updatedDate");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Electronics",
                            CreatedDate = new DateTime(2024, 7, 3, 11, 31, 55, 325, DateTimeKind.Local).AddTicks(5093),
                            Description = "A high-performance laptop for work and gaming.",
                            ImageUrl = "http://example.com/laptop.jpg",
                            IsAvailable = true,
                            Name = "Laptop",
                            Price = 999.99m,
                            StockQuantity = 10,
                            UpdatedDate = new DateTime(2025, 1, 3, 11, 31, 55, 325, DateTimeKind.Local).AddTicks(5155)
                        },
                        new
                        {
                            Id = 2,
                            Category = "Electronics",
                            CreatedDate = new DateTime(2024, 10, 3, 11, 31, 55, 325, DateTimeKind.Local).AddTicks(5159),
                            Description = "A modern smartphone with excellent camera quality.",
                            ImageUrl = "http://example.com/smartphone.jpg",
                            IsAvailable = true,
                            Name = "Smartphone",
                            Price = 799.99m,
                            StockQuantity = 20,
                            UpdatedDate = new DateTime(2025, 1, 3, 11, 31, 55, 325, DateTimeKind.Local).AddTicks(5161)
                        },
                        new
                        {
                            Id = 3,
                            Category = "Accessories",
                            CreatedDate = new DateTime(2024, 12, 3, 11, 31, 55, 325, DateTimeKind.Local).AddTicks(5165),
                            Description = "Noise-canceling headphones for immersive sound.",
                            ImageUrl = "http://example.com/headphones.jpg",
                            IsAvailable = true,
                            Name = "Headphones",
                            Price = 199.99m,
                            StockQuantity = 50,
                            UpdatedDate = new DateTime(2025, 1, 3, 11, 31, 55, 325, DateTimeKind.Local).AddTicks(5166)
                        },
                        new
                        {
                            Id = 4,
                            Category = "Electronics",
                            CreatedDate = new DateTime(2024, 11, 3, 11, 31, 55, 325, DateTimeKind.Local).AddTicks(5169),
                            Description = "A 24-inch monitor with stunning picture quality.",
                            ImageUrl = "http://example.com/monitor.jpg",
                            IsAvailable = true,
                            Name = "Monitor",
                            Price = 299.99m,
                            StockQuantity = 5,
                            UpdatedDate = new DateTime(2025, 1, 3, 11, 31, 55, 325, DateTimeKind.Local).AddTicks(5170)
                        },
                        new
                        {
                            Id = 5,
                            Category = "Electronics",
                            CreatedDate = new DateTime(2024, 8, 3, 11, 31, 55, 325, DateTimeKind.Local).AddTicks(5172),
                            Description = "A lightweight tablet, perfect for reading and browsing.",
                            ImageUrl = "http://example.com/tablet.jpg",
                            IsAvailable = true,
                            Name = "Tablet",
                            Price = 499.99m,
                            StockQuantity = 15,
                            UpdatedDate = new DateTime(2025, 1, 3, 11, 31, 55, 325, DateTimeKind.Local).AddTicks(5174)
                        },
                        new
                        {
                            Id = 6,
                            Category = "Furniture",
                            CreatedDate = new DateTime(2024, 9, 3, 11, 31, 55, 325, DateTimeKind.Local).AddTicks(5176),
                            Description = "Ergonomic gaming chair for extended comfort.",
                            ImageUrl = "http://example.com/gamingchair.jpg",
                            IsAvailable = true,
                            Name = "Gaming Chair",
                            Price = 199.99m,
                            StockQuantity = 25,
                            UpdatedDate = new DateTime(2025, 1, 3, 11, 31, 55, 325, DateTimeKind.Local).AddTicks(5177)
                        },
                        new
                        {
                            Id = 7,
                            Category = "Accessories",
                            CreatedDate = new DateTime(2024, 7, 3, 11, 31, 55, 325, DateTimeKind.Local).AddTicks(5180),
                            Description = "Mechanical keyboard with customizable RGB lighting.",
                            ImageUrl = "http://example.com/keyboard.jpg",
                            IsAvailable = true,
                            Name = "Keyboard",
                            Price = 89.99m,
                            StockQuantity = 30,
                            UpdatedDate = new DateTime(2025, 1, 3, 11, 31, 55, 325, DateTimeKind.Local).AddTicks(5181)
                        },
                        new
                        {
                            Id = 8,
                            Category = "Accessories",
                            CreatedDate = new DateTime(2024, 11, 3, 11, 31, 55, 325, DateTimeKind.Local).AddTicks(5183),
                            Description = "A wireless mouse with high precision and long battery life.",
                            ImageUrl = "http://example.com/mouse.jpg",
                            IsAvailable = true,
                            Name = "Wireless Mouse",
                            Price = 49.99m,
                            StockQuantity = 40,
                            UpdatedDate = new DateTime(2025, 1, 3, 11, 31, 55, 325, DateTimeKind.Local).AddTicks(5185)
                        },
                        new
                        {
                            Id = 9,
                            Category = "Electronics",
                            CreatedDate = new DateTime(2024, 6, 3, 11, 31, 55, 325, DateTimeKind.Local).AddTicks(5187),
                            Description = "A stylish smartwatch with health tracking features.",
                            ImageUrl = "http://example.com/smartwatch.jpg",
                            IsAvailable = true,
                            Name = "Smartwatch",
                            Price = 299.99m,
                            StockQuantity = 10,
                            UpdatedDate = new DateTime(2025, 1, 3, 11, 31, 55, 325, DateTimeKind.Local).AddTicks(5188)
                        },
                        new
                        {
                            Id = 10,
                            Category = "Accessories",
                            CreatedDate = new DateTime(2024, 5, 3, 11, 31, 55, 325, DateTimeKind.Local).AddTicks(5191),
                            Description = "A 1TB external hard drive for backups and storage.",
                            ImageUrl = "http://example.com/harddrive.jpg",
                            IsAvailable = true,
                            Name = "External Hard Drive",
                            Price = 149.99m,
                            StockQuantity = 20,
                            UpdatedDate = new DateTime(2025, 1, 3, 11, 31, 55, 325, DateTimeKind.Local).AddTicks(5192)
                        });
                });

            modelBuilder.Entity("ThMoCo.Api.DTO.AppUser", b =>
                {
                    b.HasOne("ThMoCo.Api.DTO.Address", "Address")
                        .WithOne()
                        .HasForeignKey("ThMoCo.Api.DTO.AppUser", "AddressId");

                    b.HasOne("ThMoCo.Api.DTO.PaymentCard", "PaymentCard")
                        .WithOne()
                        .HasForeignKey("ThMoCo.Api.DTO.AppUser", "PaymentCardId");

                    b.Navigation("Address");

                    b.Navigation("PaymentCard");
                });

            modelBuilder.Entity("ThMoCo.Api.DTO.OrderItem", b =>
                {
                    b.HasOne("ThMoCo.Api.DTO.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ThMoCo.Api.DTO.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
