// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThMoCo.Api.Data;

#nullable disable

namespace ThMoCo.Api.Data.Migrations
{
    [DbContext(typeof(ProductsContext))]
    [Migration("20241220001830_AddedSeedData")]
    partial class AddedSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ThMoCo.Api.DTO.ProductDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Supplier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Electronics",
                            CreatedDate = new DateTime(2024, 6, 20, 0, 18, 29, 932, DateTimeKind.Local).AddTicks(63),
                            Description = "A high-performance laptop for work and gaming.",
                            ImageUrl = "http://example.com/laptop.jpg",
                            IsAvailable = true,
                            Name = "Laptop",
                            Price = 999.99m,
                            StockQuantity = 10,
                            UpdatedDate = new DateTime(2024, 12, 20, 0, 18, 29, 932, DateTimeKind.Local).AddTicks(135)
                        },
                        new
                        {
                            Id = 2,
                            Category = "Electronics",
                            CreatedDate = new DateTime(2024, 9, 20, 0, 18, 29, 932, DateTimeKind.Local).AddTicks(141),
                            Description = "A modern smartphone with excellent camera quality.",
                            ImageUrl = "http://example.com/smartphone.jpg",
                            IsAvailable = true,
                            Name = "Smartphone",
                            Price = 799.99m,
                            StockQuantity = 20,
                            UpdatedDate = new DateTime(2024, 12, 20, 0, 18, 29, 932, DateTimeKind.Local).AddTicks(143)
                        },
                        new
                        {
                            Id = 3,
                            Category = "Accessories",
                            CreatedDate = new DateTime(2024, 11, 20, 0, 18, 29, 932, DateTimeKind.Local).AddTicks(147),
                            Description = "Noise-canceling headphones for immersive sound.",
                            ImageUrl = "http://example.com/headphones.jpg",
                            IsAvailable = true,
                            Name = "Headphones",
                            Price = 199.99m,
                            StockQuantity = 50,
                            UpdatedDate = new DateTime(2024, 12, 20, 0, 18, 29, 932, DateTimeKind.Local).AddTicks(150)
                        },
                        new
                        {
                            Id = 4,
                            Category = "Electronics",
                            CreatedDate = new DateTime(2024, 10, 20, 0, 18, 29, 932, DateTimeKind.Local).AddTicks(154),
                            Description = "A 24-inch monitor with stunning picture quality.",
                            ImageUrl = "http://example.com/monitor.jpg",
                            IsAvailable = true,
                            Name = "Monitor",
                            Price = 299.99m,
                            StockQuantity = 5,
                            UpdatedDate = new DateTime(2024, 12, 20, 0, 18, 29, 932, DateTimeKind.Local).AddTicks(156)
                        },
                        new
                        {
                            Id = 5,
                            Category = "Electronics",
                            CreatedDate = new DateTime(2024, 7, 20, 0, 18, 29, 932, DateTimeKind.Local).AddTicks(160),
                            Description = "A lightweight tablet, perfect for reading and browsing.",
                            ImageUrl = "http://example.com/tablet.jpg",
                            IsAvailable = true,
                            Name = "Tablet",
                            Price = 499.99m,
                            StockQuantity = 15,
                            UpdatedDate = new DateTime(2024, 12, 20, 0, 18, 29, 932, DateTimeKind.Local).AddTicks(162)
                        },
                        new
                        {
                            Id = 6,
                            Category = "Furniture",
                            CreatedDate = new DateTime(2024, 8, 20, 0, 18, 29, 932, DateTimeKind.Local).AddTicks(166),
                            Description = "Ergonomic gaming chair for extended comfort.",
                            ImageUrl = "http://example.com/gamingchair.jpg",
                            IsAvailable = true,
                            Name = "Gaming Chair",
                            Price = 199.99m,
                            StockQuantity = 25,
                            UpdatedDate = new DateTime(2024, 12, 20, 0, 18, 29, 932, DateTimeKind.Local).AddTicks(168)
                        },
                        new
                        {
                            Id = 7,
                            Category = "Accessories",
                            CreatedDate = new DateTime(2024, 6, 20, 0, 18, 29, 932, DateTimeKind.Local).AddTicks(172),
                            Description = "Mechanical keyboard with customizable RGB lighting.",
                            ImageUrl = "http://example.com/keyboard.jpg",
                            IsAvailable = true,
                            Name = "Keyboard",
                            Price = 89.99m,
                            StockQuantity = 30,
                            UpdatedDate = new DateTime(2024, 12, 20, 0, 18, 29, 932, DateTimeKind.Local).AddTicks(174)
                        },
                        new
                        {
                            Id = 8,
                            Category = "Accessories",
                            CreatedDate = new DateTime(2024, 10, 20, 0, 18, 29, 932, DateTimeKind.Local).AddTicks(178),
                            Description = "A wireless mouse with high precision and long battery life.",
                            ImageUrl = "http://example.com/mouse.jpg",
                            IsAvailable = true,
                            Name = "Wireless Mouse",
                            Price = 49.99m,
                            StockQuantity = 40,
                            UpdatedDate = new DateTime(2024, 12, 20, 0, 18, 29, 932, DateTimeKind.Local).AddTicks(180)
                        },
                        new
                        {
                            Id = 9,
                            Category = "Electronics",
                            CreatedDate = new DateTime(2024, 5, 20, 0, 18, 29, 932, DateTimeKind.Local).AddTicks(184),
                            Description = "A stylish smartwatch with health tracking features.",
                            ImageUrl = "http://example.com/smartwatch.jpg",
                            IsAvailable = true,
                            Name = "Smartwatch",
                            Price = 299.99m,
                            StockQuantity = 10,
                            UpdatedDate = new DateTime(2024, 12, 20, 0, 18, 29, 932, DateTimeKind.Local).AddTicks(186)
                        },
                        new
                        {
                            Id = 10,
                            Category = "Accessories",
                            CreatedDate = new DateTime(2024, 4, 20, 0, 18, 29, 932, DateTimeKind.Local).AddTicks(189),
                            Description = "A 1TB external hard drive for backups and storage.",
                            ImageUrl = "http://example.com/harddrive.jpg",
                            IsAvailable = true,
                            Name = "External Hard Drive",
                            Price = 149.99m,
                            StockQuantity = 20,
                            UpdatedDate = new DateTime(2024, 12, 20, 0, 18, 29, 932, DateTimeKind.Local).AddTicks(191)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
